# Generated by Django 3.1.4 on 2020-12-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_finished_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='fine',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
