# Generated by Django 3.1.4 on 2020-12-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_request_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='fine',
        ),
    ]
